- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure endpoint control settings.
    fortios_endpoint_control_settings:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      endpoint_control_settings:
        download_location: "fortiguard"
        forticlient_avdb_update_interval: "8"
        forticlient_dereg_unsupported_client: "enable"
        forticlient_ems_rest_api_call_timeout: "5500"
        forticlient_keepalive_interval: "40"
        forticlient_offline_grace: "disable"
        forticlient_reg_key_enforce: "disable"
        forticlient_reg_timeout: "7"
        forticlient_sys_update_interval: "710"
        forticlient_user_avatar: "enable"
        forticlient_warning_interval: "2"
